{% set name = 'bob.learn.tensorflow' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - bob_tf_compute_statistics.py = bob.learn.tensorflow.script.compute_statistics:main
    - bob_tf_db_to_tfrecords       = bob.learn.tensorflow.script.db_to_tfrecords:main
    - bob_tf_train_generic         = bob.learn.tensorflow.script.train_generic:main
    - bob_tf_eval_generic          = bob.learn.tensorflow.script.eval_generic:main
    - bob_tf_train_and_evaluate    = bob.learn.tensorflow.script.train_and_evaluate:main
    - bob_tf_predict_generic       = bob.learn.tensorflow.script.predict_generic:main
    - bob_tf_predict_bio           = bob.learn.tensorflow.script.predict_bio:main
    
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.blitz
    - bob.core
    - bob.db.base
    - bob.extension
    - bob.io.base
    - bob.io.image
    - bob.learn.activation
    - bob.learn.em
    - bob.learn.linear
    - bob.ip.base
    - bob.math
    - bob.measure
    - bob.sp
    - bob.db.mnist
    - bob.db.atnt
    - bob.bio.base
    - scipy {{ scipy }}
    - six {{ six }}
  run:
    - python
    - setuptools
    - scipy
    - six
    - tensorflow >=1.4

test:
  imports:
    - {{ name }}
  commands:
    - bob_tf_compute_statistics.py --help
    - bob_tf_db_to_tfrecords --help
    - bob_tf_train_generic --help
    - bob_tf_eval_generic --help
    - bob_tf_train_and_evaluate --help
    - bob_tf_predict_generic --help
    - bob_tf_predict_bio --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - bob.io.image
    - bob.db.atnt
    - matplotlib
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Bob support for tensorflow
  license_family: BSD
