{% set name = 'bob.learn.tensorflow' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.io.base
    - bob.io.image
    - bob.measure
    - click {{ click }}
    - click-plugins {{ click_plugins }}
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - {{ pin_compatible('click') }}
    - {{ pin_compatible('click-plugins') }}
    - tensorflow >=2.2
    - scikit-learn {{ scikit_learn }}    

test:
  imports:
    - {{ name }}
  commands:
    - bob tf --help
    - bob tf datasets-to-tfrecords --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - bob.io.image
    - bob.db.atnt
    - matplotlib
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Bob support for tensorflow
  license_family: BSD
